package Main.Employee;

import Main.Main;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.LinkedBlockingQueue;

public class DataPanel extends Employee implements DataTeam {
    private static final String GUESTS = Main.HOTEL_PATH + "/" + "Guest.txt";
    private static final String RESERVATION = Main.HOTEL_PATH + "/" + "Reservation.txt";
    private static final String PAST_RESERVATIONS = Main.HOTEL_PATH + "/" + "Past_Reservation.txt";
    private static final String ROOM = Main.HOTEL_PATH + "/" + "Room.txt";

    private List<String[]> guests = new ArrayList<>();
    private List<String[]> reservations = new ArrayList<>();
    private List<String[]> pastReservations = new ArrayList<>();
    private List<String[]> rooms = new ArrayList<>();
    private Map<String, Integer> guestVisitCount = new HashMap<>();

    // Shared queue for requests from executives
    private static final LinkedBlockingQueue<String> requestQueue = new LinkedBlockingQueue<>();

    public DataPanel(int staffID, String name, String role) {
        super(staffID, name, role);
    }

    // Add a new report request from Executive
    public static void addRequest(String request) {
        try {
            requestQueue.put(request);
            System.out.println("New report request added: " + request);
        } catch (InterruptedException e) {
            System.out.println(" Failed to add request: " + e.getMessage());
        }
    }

    // View all pending requests
    public static void viewRequests() {
        if (requestQueue.isEmpty()) {
            System.out.println("📭 No pending report requests.");
            return;
        }

        System.out.println("\n===== PENDING REPORT REQUESTS =====");
        int i = 1;
        for (String req : requestQueue) {
            System.out.println(i++ + ". " + req);
        }
    }

    // Complete (remove) a request by index
    public static void completeRequest(int index) {
        if (index <= 0 || index > requestQueue.size()) {
            System.out.println("Invalid request number.");
            return;
        }

        List<String> list = new ArrayList<>(requestQueue);
        String done = list.get(index - 1);
        requestQueue.remove(done);
        System.out.println("Request completed and removed: " + done);
    }

    @Override
    public void pullData() {
        try {
            guests = loadFile(GUESTS);
            reservations = loadFile(RESERVATION);
            pastReservations = loadFile(PAST_RESERVATIONS);
            rooms = loadFile(ROOM);
            System.out.println("Data pulled successfully from all sources.");
        } catch (IOException e) {
            System.out.println("Error reading data files: " + e.getMessage());
        }
    }

    @Override
    public void analyzeData() {
        if (guests.isEmpty() || (reservations.isEmpty() && pastReservations.isEmpty())) {
            System.out.println("Please pull data first before analysis.");
            return;
        }

        Scanner sc = new Scanner(System.in);
        System.out.println("\n--- Choose Data Analysis Type ---");
        System.out.println("1. Guest Data Analysis");
        System.out.println("2. Reservation Data Analysis");
        System.out.println("3. Past Reservation Analysis");
        System.out.print("Enter choice (1–3): ");

        int choice = sc.nextInt();
        sc.nextLine();

        if (choice == 1) {
            analyzeGuestData();
        } else if (choice == 2) {
            analyzeReservationData();
        } else if (choice == 3) {
            analyzePastReservationData();
        } else {
            System.out.println("Invalid choice. Please enter 1–3.");
        }
    }

    @Override
    public void writeReport() {
        Scanner sc = new Scanner(System.in);

        try {
            PrintWriter writer = new PrintWriter("DataReport.txt");

            writer.println("====== Hotel Data Summary ======");
            writer.println("Generated by: " + getName() + " (" + role() + ")");
            writer.println("================================\n");

            writer.println("Total Guests: " + guests.size());
            writer.println("Active Reservations: " + reservations.size());
            writer.println("Past Reservations: " + pastReservations.size());
            writer.println();

            if (!guestVisitCount.isEmpty()) {
                writer.println("Top Returning Guests:");
                for (Map.Entry<String, Integer> entry : guestVisitCount.entrySet()) {
                    writer.println(entry.getKey() + " - " + entry.getValue() + " visits");
                }
                writer.println();
            }

            System.out.println("\n--- Write Your Report Section ---");
            System.out.println("(Type your analysis/comments below. Enter a blank line to finish.)");
            System.out.println("---------------------------------------------------------------");

            while (true) {
                String line = sc.nextLine();
                if (line.trim().isEmpty()) {
                    break;
                }
                writer.println(line);
            }

            writer.println("\nReport generated successfully.");
            writer.close();

            File file = new File("DataReport.txt");
            System.out.println("Report successfully written to: " + file.getAbsolutePath());

        } catch (IOException e) {
            System.out.println("Error writing report: " + e.getMessage());
        }
    }

    @Override
    public void notify_exec() {
        System.out.println("\n [Notification] Data report generated successfully.");
        System.out.println("Executives have been notified of the latest analytics update.");
    }

    private List<String[]> loadFile(String filePath) throws IOException {
        List<String[]> data = new ArrayList<>();
        List<String> lines = Files.readAllLines(Paths.get(filePath));

        for (String line : lines) {
            if (!line.trim().isEmpty()) {
                data.add(line.split(","));
            }
        }

        return data;
    }

    private void analyzeGuestData() {
        System.out.println("\n--- Guest Data Analysis ---");
        System.out.println("Total Guests: " + guests.size());

        Set<String> uniqueGuests = new HashSet<>();
        int duplicates = 0;

        for (String[] g : guests) {
            String guestName = g[0].trim();
            if (!uniqueGuests.add(guestName)) {
                duplicates++;
            }
        }

        System.out.println("Unique Guests: " + uniqueGuests.size());
        System.out.println("Duplicate Entries Found: " + duplicates);
    }

    private void analyzeReservationData() {
        System.out.println("\n--- Reservation Data Analysis ---");
        System.out.println("Active Reservations: " + reservations.size());

        Map<String, Integer> roomBookings = new HashMap<>();
        for (String[] record : reservations) {
            if (record.length >= 3) {
                String roomNumber = record[2].trim();
                roomBookings.put(roomNumber, roomBookings.getOrDefault(roomNumber, 0) + 1);
            }
        }

        System.out.println("Bookings per Room:");
        for (Map.Entry<String, Integer> entry : roomBookings.entrySet()) {
            System.out.println("Room " + entry.getKey() + ": " + entry.getValue() + " active reservations");
        }

        if (!rooms.isEmpty()) {
            Map<String, Integer> typeCount = new HashMap<>();
            for (String[] r : rooms) {
                if (r.length >= 2) {
                    String type = r[1].trim();
                    typeCount.put(type, typeCount.getOrDefault(type, 0) + 1);
                }
            }

            System.out.println("\nRoom Types Available:");
            for (Map.Entry<String, Integer> entry : typeCount.entrySet()) {
                System.out.println(entry.getKey() + ": " + entry.getValue() + " rooms");
            }
        }
    }

    private void analyzePastReservationData() {
        System.out.println("\n--- Past Reservation Data Analysis ---");
        System.out.println("Total Past Reservations: " + pastReservations.size());

        guestVisitCount.clear();
        for (String[] record : pastReservations) {
            if (record.length >= 2) {
                String guestName = record[1].trim();
                guestVisitCount.put(guestName, guestVisitCount.getOrDefault(guestName, 0) + 1);
            }
        }

        System.out.println("Guest Visit Counts:");
        for (Map.Entry<String, Integer> entry : guestVisitCount.entrySet()) {
            System.out.println(entry.getKey() + " - " + entry.getValue() + " visits");
        }
    }
}